"""Push log exports to a GitHub repository for persistent backup."""

import base64
from datetime import datetime
from pathlib import Path
from typing import Optional

import requests
from loguru import logger


def _ensure_repo_initialized(token: str, repo: str, headers: dict) -> tuple[bool, str]:
    """Check repo exists and has a default branch; create README if empty."""
    r = requests.get(f"https://api.github.com/repos/{repo}", headers=headers, timeout=10)
    if r.status_code == 404:
        return False, f"Repo '{repo}' not found. Create it at github.com/new (make it private)."
    if r.status_code == 401:
        return False, "GitHub token is invalid or expired. Generate a new one with 'repo' scope."
    if r.status_code != 200:
        return False, f"GitHub API error {r.status_code}: {r.text[:200]}"

    # Check if repo has a default branch (i.e. at least one commit)
    default_branch = r.json().get("default_branch")
    branch_url = f"https://api.github.com/repos/{repo}/branches/{default_branch}"
    br = requests.get(branch_url, headers=headers, timeout=10)
    if br.status_code == 404:
        # Empty repo — create an initial README to initialize it
        init = requests.put(
            f"https://api.github.com/repos/{repo}/contents/README.md",
            headers=headers,
            json={
                "message": "Initialize backup repo",
                "content": base64.b64encode(b"# POLI 319 Log Backups\nAuto-generated by the research assistant.\n").decode(),
            },
            timeout=15,
        )
        if init.status_code not in (200, 201):
            return False, f"Could not initialize empty repo: {init.status_code} {init.text[:200]}"
        logger.info(f"Initialized empty repo {repo} with README")

    return True, ""


def _github_put(token: str, repo: str, path: str, content_bytes: bytes, message: str, headers: dict) -> tuple[bool, str]:
    """Create or update a file in a GitHub repo via the REST API."""
    url = f"https://api.github.com/repos/{repo}/contents/{path}"

    existing = requests.get(url, headers=headers, timeout=10)
    sha = existing.json().get("sha") if existing.status_code == 200 else None

    payload = {
        "message": message,
        "content": base64.b64encode(content_bytes).decode(),
    }
    if sha:
        payload["sha"] = sha

    r = requests.put(url, headers=headers, json=payload, timeout=15)
    if r.status_code in (200, 201):
        return True, ""
    return False, f"{r.status_code}: {r.text[:300]}"


def push_logs_to_github(db_path: Path, token: str, repo: str) -> tuple[bool, str]:
    """
    Export all log tables as CSVs and push them to a GitHub repo.

    Returns:
        (success, error_message)
    """
    import src.logging.db as db
    import pandas as pd

    headers = {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github.v3+json",
    }

    # Verify repo exists and is initialized
    ok, err = _ensure_repo_initialized(token, repo, headers)
    if not ok:
        return False, err

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M UTC")
    commit_msg = f"Auto-backup: {timestamp}"

    exports = {
        "logs/sessions.csv": db.get_all_sessions(db_path).to_csv(index=False).encode(),
        "logs/group_summaries.csv": db.get_group_summaries(db_path).to_csv(index=False).encode(),
        "logs/disclosures.csv": db.get_all_disclosures(db_path).to_csv(index=False).encode(),
        "logs/feedback.csv": db.get_all_feedback(db_path).to_csv(index=False).encode(),
    }

    sessions = db.get_all_sessions(db_path)
    if not sessions.empty:
        all_msgs = []
        for sid in sessions["session_id"]:
            msgs = db.get_session_messages(db_path, sid)
            if not msgs.empty:
                msgs.insert(0, "session_id", sid)
                all_msgs.append(msgs)
        if all_msgs:
            exports["logs/all_messages.csv"] = pd.concat(all_msgs, ignore_index=True).to_csv(index=False).encode()

    errors = []
    for path, content in exports.items():
        ok, err = _github_put(token, repo, path, content, commit_msg, headers)
        if ok:
            logger.info(f"Backed up {path} → github:{repo}")
        else:
            logger.error(f"Failed to push {path}: {err}")
            errors.append(f"{path}: {err}")

    if errors:
        return False, "\n".join(errors)
    return True, ""


def get_github_config() -> tuple[Optional[str], Optional[str]]:
    """Read GitHub token and backup repo from Streamlit secrets."""
    try:
        import streamlit as st
        token = st.secrets.get("GITHUB_TOKEN")
        repo = st.secrets.get("BACKUP_REPO")
        return token, repo
    except Exception:
        return None, None
